### ISSUE TITLE
child의 key관련 에러 콘솔 출력됨.

### ISSUE THREAD

**Issue by gboycdw** [gboycdw/gaMeZone#108]
![image](https://github.com/gboycdw/gaMeZone/assets/59162652/d2eab60e-864b-4388-973e-caee18a247cc)
![image](https://github.com/gboycdw/gaMeZone/assets/59162652/83984b54-a569-4424-a120-9d1b5e578a82)

거의 모든 map으로 뿌린 페이지에서 확인 됨.
이 오류가 대체 원인이 뭘지..

**Comment by ksknote** [comment]
map 으로 렌더링 할 때 최상위 요소에 key prop을 주니 해결이 되었습니다.
