### ISSUE TITLE
관리자페이지 창 크기를 줄였을 때 버튼을 누를 수 없는 문제

### ISSUE THREAD

**Issue by gboycdw** [gboycdw/gaMeZone#115]
![image](https://github.com/gboycdw/gaMeZone/assets/59162652/0d4c3956-7470-44a1-b0c7-a32dfd8f3694)

**Comment by zhal7779** [comment]
이거 해보니깐 간단히 할 수 있는 문제가 아니고 미디어 쿼리로 해서 대공사를 해야되더라구,,,, 구현 다 하고 맨 마지막에 하는게 좋을 거 같앙
