### ISSUE TITLE
1차 목표기간 내 남은 작업소요 체크

### ISSUE THREAD

**Issue by gboycdw** [gboycdw/gaMeZone#121]
댓글로

**Comment by 02rynn** [comment]
프로필 사진 수정 (근데 업로드와 미리보기를 같이하고 싶은데 처음해보는거라.. 조금 걸릴듯 ㅎㅎ..)
api연결하기
내가 댓글 단 글 불러오기

**Comment by uniqueeest** [comment]
1. Comment API 연결
2. 커뮤니티 페이지에서 mainPage로 갈 수 있도록 UI 구현
3. Post, Comment User 정보와 연결

**Comment by ksknote** [comment]
1. 명예의 전당 구현 (현재 레이아웃만 완성된 상태)
2. 게임 실행페이지 내 게임 메뉴얼 api 연결

**Comment by gboycdw** [comment]
명예의전당 출력 관련 score DB에서 각 유저들의 평균or최고점수를 바탕으로 유저 랭킹을 산출하는 기능 제작 필요함.

**Comment by zhal7779** [comment]
관리자 페이지 
- 게임 정보 관리 (게임정보 추가 페이지 구현, 게임 정보 수정 페이지 구현)
- 회원관리(수정, 삭제 페이지 구현)
- 게임 기록관리 (삭제 페이지 구현)

**Comment by wlwhsxz** [comment]
1. 토큰을 가진 유저 login 페이지 접근 시 main 페이지로 redirect
2. auth middleware 만들기 (useContext 관리 방법 고민)
3. refresh 토큰 구상

**Comment by wlwhsxz** [comment]
1. 토큰을 가진 유저 login 페이지 접근 시 main 페이지로 redirect
2. nickname으로 유저 검색 기능 컴포넌트화(랭킹, 관리자 페이지 사용 예상)
3. auth middleware 만들기 (useContext 관리 방법 고민)
4. refresh 토큰 구상

추가 작업 예상
1. google, kakao 로그인
2. ...
