### ISSUE TITLE
로그인을 안 해도 커뮤니티-글쓰기/댓글쓰기가 활성화되는 문제

### ISSUE THREAD

**Issue by gboycdw** [gboycdw/gaMeZone#158]
+ 권한 오류로 에러가 발생함

![image](https://github.com/gboycdw/gaMeZone/assets/59162652/e1f8ff64-8cf8-485d-a419-dcf5bea1b843)

**Comment by uniqueeest** [comment]
현재 게시글 카테고리 나누는 작업 중이라 오류 발생함

**Comment by uniqueeest** [comment]
로그인을 안해도 token이 local Storage에 남아있으면 글쓰기 창이 보일 수 있음.

**Comment by gboycdw** [comment]
이슈 해결 확인됨
