### ISSUE TITLE
DB에 상대경로로 저장한 image를 렌더링하지 못하는 문제

### ISSUE THREAD

**Issue by gboycdw** [gboycdw/gaMeZone#87]
기존에는 require 혹은 import로 이미지를 직접 가져와서 화면에 띄웠으나,

DB에 저장되어 있던 상대 경로 ``gameImageUrl : "../../images/gomao.png"`` 를 사용하여 이미지를 렌더링하려고 시도하였으나,
이미지가 뜨지 않음.

**Comment by ksknote** [comment]
public 파일에 있는 이미지는 서버에 통신이 가능하다. 
src 경로를 http://localhost:8080/public/images/img-1682667199359.png 이와 같이 절대 경로를 입력하여  해결하였다. 얏호!

**Comment by wlwhsxz** [comment]
얏호! 덕분에 한 줌의 지식 겟또! ^^

**Comment by gboycdw** [comment]
무한감사
