### ISSUE TITLE
각 페이지에서 author 확인하는 방법 결정해야 함

### ISSUE THREAD

**Issue by gboycdw** [gboycdw/gaMeZone#89]
토큰? state? 효율성 측면에서 고민해봐야 할 것임

**Comment by wlwhsxz** [comment]
옳소 옳소..!
심도있게 고민 좀 해보겠소!

**Comment by uniqueeest** [comment]
이 부분은 월요일 스크럼 때 논의하면 좋을듯! 아니면 일요일 밤

**Comment by wlwhsxz** [comment]
=> 페이지 get, post ... 등 요청 시 토큰으로 authentication 체크!

**Comment by gboycdw** [comment]
여러 페이지에서 테스트 결과 잘됨! 이슈 닫겠음.
