### ISSUE TITLE
[모든 파트] localhost:3000으로 경로를 정의해둔 것들 전부 .env로 고쳐야 함.

### ISSUE THREAD

**Issue by gboycdw** [gboycdw/gaMeZone#91]
.env 파일의 경로는 Frontend/.gitignore와 같은 경로에 생성해야 함. (package.json이 있는 위치임)
이때 각 변수명을 다음과 같이 생성해야 함 ``REACT_APP_... : ~~~~``
예시
```
REACT_APP_API_URL : http://gomao.com               <= 이때 반드시 "/"로 끝나게 하지 말것.
```
단, react-app 내장 기능이므로, dotenv 패키지를 설치하면 충돌나서 오류가 발생할 수 있음. 절대 설치하지 말것

개인별로 확인해보고 수정 완료되었거나 사용한 케이스가 없으면 댓글로 회신 바람

**Comment by wlwhsxz** [comment]
login & signup 수정 완료!

**Comment by uniqueeest** [comment]
backend파일 내부에서 dotenv install 하는거는 괜찮은건지 이슈로 남깁니다.

**Comment by wlwhsxz** [comment]
@uniqueeest React v4 이상부터는 dotenv가 내장함수로 포함되어 있어서 따로 설치 시 충돌이 발생한다고 해용.

**Comment by gboycdw** [comment]
> 

백엔드는 npm install dotenv 해도 됨
다만, process.env 사용을 위해서 프론트엔드 루트폴더에서는 절대 하면 안됨
