### ISSUE TITLE
main, main-footer 페이지에서 스크롤바가 생기는 현상

### ISSUE THREAD

**Issue by gboycdw** [gboycdw/gaMeZone#99]
어떤 margin때문에 발생하는 문제인지 아직 확인하지 못했음.

![image](https://github.com/gboycdw/gaMeZone/assets/59162652/004a7ff6-fd37-4d91-b455-e2df2387bffe)

**Comment by ksknote** [comment]
<img width="893" alt="image" src="https://github.com/gboycdw/gaMeZone/assets/125117987/d0e3dcd1-c22a-42a8-99a3-92976a51ed09">
요렇게 수정하면 스크롤이 없어지네요 ^.^  기기에 따라 다르겠지만, 최소 너비와 높이가 스크린보다 크면 스크롤이 생기는 것 같아요. 반응형까지 고려하면  minwidth, minheight 를 없애기보다는 값을 더 작게 조정해야할 것 같아요. 추가적으로 스크롤이 없어지면 아이콘 크기는 줄여야할 것 같네요.

**Comment by gboycdw** [comment]
오 일단 보이는 모든 페이지에 반영 완료

해당 css 내용을 모듈화 해야할 것 같음
